In [1]:
import quantecon as qe
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
%matplotlib inline
# importing networkx  
import networkx as nx 
# importing matplotlib.pyplot 
import matplotlib.pyplot as plt
import pandas as pd
import pydot

In [4]:
P1=[[0.0232460593460577, 0.00560174845597652, 0.0467179883425076, 0.0665592773073191, 0.857874926548139],
    [0.0136463870422535, 0.0490583821470984, 0.0166987360598636, 0.1296937249811, 0.790902769769684],
    [0.0462073802724979, 0.00163516165267978, 0.0122184468821205, 0.00806716298524617, 0.931871848207456],
    [0.0674564304316847, 0.118393449396849, 0.0945556903438833, 0.0289925763492009, 0.690601853478382],
    [0.0719504828182986, 0.237872699666635, 0.137118006112976, 0.0391436205590491, 0.513915190843042]]

In [5]:
mc1 = qe.MarkovChain(P1)
mc1.period

1

In [6]:
mc1.is_irreducible

True

In [7]:
mc1.num_communication_classes

1

In [8]:
mc1.communication_classes

[array([0, 1, 2, 3, 4])]

In [9]:
mc1.is_aperiodic

True

In [10]:
mc1.period

1

In [11]:
print(mc1.stationary_distributions)

[[0.05685    0.16432959 0.09776552 0.05201604 0.62903885]]


In [14]:
P2=[[0.003407870408, 0.01806985987, 0.01954364792, 0.01666851099, 0.9423101108],
    [0.04513286019, 0.03464884503, 0.004095797233, 0.002455417135, 0.9136670804],
    [0.04253086727, 0.003216659271, 0.1020704951, 0.005207838836, 0.8469741396],
    [0.05805748631, 0.01464032011, 0.004289838442, 0.02608821783, 0.8969241373],
    [0.04400335537, 0.05817956438, 0.004399909611, 0.01972704556, 0.8736901251]]

In [15]:
mc2 = qe.MarkovChain(P2)
mc2.period

1

In [16]:
mc2.is_irreducible

True

In [17]:
mc2.num_communication_classes

1

In [18]:
mc2.communication_classes

[array([0, 1, 2, 3, 4])]

In [19]:
mc2.is_aperiodic

True

In [20]:
mc2.period

1

In [21]:
print(mc2.stationary_distributions)

[[0.04259009 0.0540784  0.00557045 0.01870084 0.87906022]]


In [22]:
P3=[[0.03981050242,0.06495668917,0.03857361881,0.03042645428,0.8262327353],
    [0.02784335616,0.007737903625,0.005239314131,0.01637654126,0.9428028848],
    [0.09831946025,0.05926588909,0.05143485484,0.1005747777,0.6904050181],
    [0.03524268554,0.04474536887,0.06311672581,0.05203553997,0.8048596798],
    [0.04109990146,0.02135395227,0.04146709912,0.03515125786,0.8609277893]]

In [23]:
mc3 = qe.MarkovChain(P3)
mc3.period

1

In [24]:
mc3.is_irreducible

True

In [25]:
mc3.num_communication_classes

1

In [26]:
mc3.communication_classes

[array([0, 1, 2, 3, 4])]

In [27]:
mc3.is_aperiodic

True

In [28]:
mc3.period

1

In [29]:
print(mc3.stationary_distributions)

[[0.04287078 0.02534262 0.04165936 0.03783726 0.85228998]]


In [30]:
P4=[[0.0355290328,0.04511749448,0.02287085724,0.01315736716,0.8833252483],
    [0.01868372706,0.1299598041,0.1203421242,0.0682766782,0.6627376665],
    [0.005528940424,0.0389864698,0.03167713187,0.02736129022,0.8964461677],
    [0.1451803416,0.03038348942,0.0268245473,0.06509280771,0.7325188139],
    [0.07278494759,0.07677333778,0.008415631524,0.03454222864,0.8074838545]]

In [31]:
mc4 = qe.MarkovChain(P4)
mc4.period

1

In [32]:
mc4.is_irreducible

True

In [33]:
mc4.num_communication_classes

1

In [34]:
mc4.communication_classes

[array([0, 1, 2, 3, 4])]

In [35]:
mc4.is_aperiodic

True

In [36]:
mc4.period

1

In [37]:
print(mc4.stationary_distributions)

[[0.06751578 0.07627264 0.01904633 0.03665447 0.80051077]]


In [38]:
P5=[[0,0.2197192828,0.196783264,0.2492150375,0.3342824158],
    [0.2774944612,0,0.2612031801,0.2218092767,0.2394930821],
    [0.08406331128,0.171050228,0.5547862007,0,0.19010026],
    [0,0.08507360996,0.2230691724,0.332791398,0.3590658196],
    [0,0.2576231624,0.1501625937,0.4686043822,0.1236098617]]

In [39]:
mc5 = qe.MarkovChain(P5)
mc5.period

1

In [40]:
mc5.is_irreducible

True

In [41]:
mc5.num_communication_classes

1

In [42]:
mc5.communication_classes

[array([0, 1, 2, 3, 4])]

In [43]:
mc5.is_aperiodic

True

In [44]:
mc5.period

1

In [45]:
print(mc5.stationary_distributions)

[[0.06765271 0.14858183 0.3143116  0.23754354 0.23191032]]


In [46]:
P6=[[0.04093156809,0.04848782226,0.01811129584,0.04667921601,0.8457900978],
    [0.01979243132,0.08594862759,0.04605026383,0.0391250939,0.8090835834],
    [0.05491338482,0.04519347815,0.005125657309,0.04394498524,0.8508224945],
    [0.03964469824,0.0517019057,0.004791790746,0.01350249567,0.8903591096],
    [0.1155835332,0.1117185882,0.07976275684,0.04276391592,0.6501712059]]

In [47]:
mc6 = qe.MarkovChain(P6)
mc6.period

1

In [48]:
mc6.is_irreducible

True

In [49]:
mc6.num_communication_classes

1

In [50]:
mc6.communication_classes

[array([0, 1, 2, 3, 4])]

In [51]:
mc6.is_aperiodic

True

In [52]:
mc6.period

1

In [53]:
print(mc6.stationary_distributions)

[[0.09243799 0.09669347 0.06298218 0.04163022 0.70625614]]


In [54]:
P7=[[0.00685563054,0.01640025695,0.05036619569,0.01733671135,0.9090412055],
    [0.04307637385,0.04898340216,0.01226181288,0.02336216372,0.8723162474],
    [0.04578771588,0.02969407768,0.01169955505,0.01928774273,0.8935309087],
    [0.006429347006,0.162530292,0.02697881973,0.08820610567,0.7158554356],
    [0.004705016515,0.006198664368,0.04393713989,0.01195245438,0.9332067248]]

In [55]:
mc7 = qe.MarkovChain(P7)
mc7.period

1

In [56]:
mc7.is_irreducible

True

In [57]:
mc7.num_communication_classes

1

In [58]:
mc7.communication_classes

[array([0, 1, 2, 3, 4])]

In [59]:
mc7.is_aperiodic

True

In [60]:
mc7.period

1

In [61]:
print(mc7.stationary_distributions)

[[0.00684706 0.00977577 0.04208691 0.01343397 0.92785629]]


In [62]:
P8=[[0.034966972, 0.019001252, 0.007437212, 0.021869966, 0.916724599],
    [0.067111946, 0.038841389, 0.03761967, 0.004851325, 0.85157567],
    [0.178412305, 0.056370555, 0.053259225, 0.013091102, 0.698866812],
    [0.033934975, 0.041621044, 0.044161263, 0.023206893, 0.857075826],
    [0.006062262, 0.01045856, 0.011370976, 0.036688231, 0.935419971]]

In [63]:
mc8 = qe.MarkovChain(P8)
mc8.period

1

In [64]:
mc8.is_irreducible

True

In [65]:
mc8.num_communication_classes

1

In [66]:
mc8.communication_classes

[array([0, 1, 2, 3, 4])]

In [67]:
mc8.is_aperiodic

True

In [68]:
mc8.period

1

In [69]:
print(mc8.stationary_distributions)

[[0.01042529 0.01262145 0.01338055 0.03533975 0.92823296]]


In [70]:
P9=[[0.0419112, 0.003273838, 0.041035509, 0.019802569, 0.893976885],
    [0.012829874, 0.070892343, 0.020464444, 0.078811859, 0.817001481],
    [0.027566398, 0.006963401, 0.038209462, 0.03657016, 0.890690579],
    [0.061322262, 0.044443321, 0.012987395, 0.028002219, 0.853244804],
    [0.018514438, 0.110838406, 0.025720436, 0.015568023, 0.829358697]]

In [71]:
mc9 = qe.MarkovChain(P9)
mc9.period

1

In [72]:
mc9.is_irreducible

True

In [73]:
mc9.num_communication_classes

1

In [74]:
mc9.communication_classes

[array([0, 1, 2, 3, 4])]

In [75]:
mc9.is_aperiodic

True

In [76]:
mc9.period

1

In [77]:
print(mc9.stationary_distributions)

[[0.01960999 0.10054594 0.02552033 0.02282983 0.83149392]]


In [78]:
P10=[[0.228901671, 0.221733522, 0.175340485, 0.013376556, 0.360647767],
    [0.073214279, 0.028177224, 0.044248129, 0.085496174, 0.768864195],
    [0.187588521, 0.020114865, 0.199761555, 0.130093468, 0.462441592],
    [0.047096905, 0.061240716, 0.016299118, 0.003087759, 0.872275502],
    [0.046517333, 0.061923098, 0.047143953, 0.001016453, 0.843399164]]

In [79]:
mc10 = qe.MarkovChain(P10)
mc10.period

1

In [80]:
mc10.is_irreducible

True

In [81]:
mc10.num_communication_classes

1

In [82]:
mc10.communication_classes

[array([0, 1, 2, 3, 4])]

In [83]:
mc10.is_aperiodic

True

In [84]:
mc10.period

1

In [85]:
print(mc10.stationary_distributions)

[[0.070426   0.06813062 0.06546939 0.01612658 0.77984742]]
